# Generated by Django 3.0.7 on 2020-11-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0002_auto_20201113_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaCuenta',
            fields=[
                ('id_categoria_cuenta', models.AutoField(db_column='ID_CATEGORIA_CUENTA', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='NOMBRE_CATEGORIA', max_length=20)),
                ('codigo_categoria', models.IntegerField(db_column='CODIGO_CATEGORIA')),
            ],
            options={
                'db_table': 'categoria_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CicloContable',
            fields=[
                ('id_ciclo', models.AutoField(db_column='ID_CICLO', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(db_column='FECHA_INICIO')),
                ('fecha_fin', models.DateField(blank=True, db_column='FECHA_FIN', null=True)),
                ('id_usuario', models.IntegerField(db_column='ID_USUARIO')),
                ('activo', models.IntegerField(db_column='ACTIVO')),
            ],
            options={
                'db_table': 'ciclo_contable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(db_column='ID_CUENTA', primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(db_column='NOMBRE_CUENTA', max_length=30)),
                ('codigo_cuenta', models.IntegerField(db_column='CODIGO_CUENTA')),
                ('naturaleza_cuenta', models.CharField(db_column='NATURALEZA_CUENTA', max_length=20)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mayorizado',
            fields=[
                ('id_mayorizado', models.AutoField(db_column='ID_MAYORIZADO', primary_key=True, serialize=False)),
                ('saldo_mayorizado', models.DecimalField(db_column='SALDO_MAYORIZADO', decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField(db_column='FECHA_INICIO')),
                ('fecha_final', models.DateTimeField(db_column='FECHA_FINAL')),
                ('naturaleza_mayorizado', models.CharField(db_column='NATURALEZA_MAYORIZADO', max_length=20)),
            ],
            options={
                'db_table': 'mayorizado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartidaCuenta',
            fields=[
                ('id_partidacuenta', models.AutoField(db_column='ID_PARTIDACUENTA', primary_key=True, serialize=False)),
                ('naturaleza_cuentapartida', models.CharField(db_column='NATURALEZA_CUENTAPARTIDA', max_length=20)),
                ('saldo_partidacuenta', models.DecimalField(db_column='SALDO_PARTIDACUENTA', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'partida_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartidaDiario',
            fields=[
                ('id_partida', models.AutoField(db_column='ID_PARTIDA', primary_key=True, serialize=False)),
                ('fecha_partida', models.DateField(db_column='FECHA_PARTIDA')),
                ('saldo_partida', models.DecimalField(db_column='SALDO_PARTIDA', decimal_places=2, max_digits=10)),
                ('descripcion_partida', models.CharField(db_column='DESCRIPCION_PARTIDA', max_length=200)),
                ('usuario_responsable', models.IntegerField(blank=True, db_column='USUARIO_RESPONSABLE', null=True)),
            ],
            options={
                'db_table': 'partida_diario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id_tipo_cuenta', models.AutoField(db_column='ID_TIPO_CUENTA', primary_key=True, serialize=False)),
                ('nombre_tipo_cuenta', models.CharField(db_column='NOMBRE_TIPO_CUENTA', max_length=30)),
                ('codigo_tipo', models.IntegerField(db_column='CODIGO_TIPO')),
            ],
            options={
                'db_table': 'tipo_cuenta',
                'managed': False,
            },
        ),
    ]
