# Generated by Django 3.0.7 on 2020-11-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_catego'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoCif',
            fields=[
                ('id_costo_cif', models.AutoField(db_column='ID_COSTO_CIF', primary_key=True, serialize=False)),
                ('metodo_base', models.CharField(db_column='METODO_BASE', max_length=40)),
                ('valor_base', models.DecimalField(db_column='VALOR_BASE', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'costo_cif',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostoIndirecto',
            fields=[
                ('id_costo_indirecto', models.AutoField(db_column='ID_COSTO_INDIRECTO', primary_key=True, serialize=False)),
                ('nombre_costo_indirecto', models.CharField(db_column='NOMBRE_COSTO_INDIRECTO', max_length=30)),
                ('descripcion_costo_indirecto', models.CharField(db_column='DESCRIPCION_COSTO_INDIRECTO', max_length=200)),
                ('valor_costo_indirecto', models.DecimalField(db_column='VALOR_COSTO_INDIRECTO', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'costo_indirecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostoInventario',
            fields=[
                ('id_costo_inventario', models.AutoField(db_column='ID_COSTO_INVENTARIO', primary_key=True, serialize=False)),
                ('tipo_costo_inventario', models.CharField(db_column='TIPO_COSTO_INVENTARIO', max_length=15)),
                ('nombre_inventario', models.CharField(db_column='NOMBRE_INVENTARIO', max_length=30)),
            ],
            options={
                'db_table': 'costo_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostoMod',
            fields=[
                ('id_costo_mod', models.AutoField(db_column='ID_COSTO_MOD', primary_key=True, serialize=False)),
                ('salario_diario', models.DecimalField(db_column='SALARIO_DIARIO', decimal_places=2, max_digits=10)),
                ('dias_trabajados', models.IntegerField(db_column='DIAS_TRABAJADOS')),
                ('dias_aguinaldo', models.IntegerField(db_column='DIAS_AGUINALDO')),
                ('dias_vacaciones', models.IntegerField(db_column='DIAS_VACACIONES')),
                ('porcentaje_vacaciones', models.DecimalField(db_column='PORCENTAJE_VACACIONES', decimal_places=2, max_digits=10)),
                ('porcentaje_seguro', models.DecimalField(db_column='PORCENTAJE_SEGURO', decimal_places=2, max_digits=10)),
                ('porcentaje_afp', models.DecimalField(db_column='PORCENTAJE_AFP', decimal_places=2, max_digits=10)),
                ('numero_trabajadores', models.IntegerField(db_column='NUMERO_TRABAJADORES')),
                ('porcentaje_insaforp', models.DecimalField(blank=True, db_column='PORCENTAJE_INSAFORP', decimal_places=2, max_digits=10, null=True)),
                ('factor_recargo', models.DecimalField(blank=True, db_column='FACTOR_RECARGO', decimal_places=2, max_digits=10, null=True)),
                ('horas_trabajadas', models.DecimalField(db_column='HORAS_TRABAJADAS', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'costo_mod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionInventario',
            fields=[
                ('id_transaccion_inventario', models.AutoField(db_column='ID_TRANSACCION_INVENTARIO', primary_key=True, serialize=False)),
                ('fecha_transaccion_inventario', models.DateField(db_column='FECHA_TRANSACCION_INVENTARIO')),
                ('monto_transaccion_inventario', models.DecimalField(db_column='MONTO_TRANSACCION_INVENTARIO', decimal_places=2, max_digits=10)),
                ('compra', models.IntegerField(db_column='COMPRA')),
                ('cantidad_transaccion_inventario', models.IntegerField(db_column='CANTIDAD_TRANSACCION_INVENTARIO')),
            ],
            options={
                'db_table': 'transaccion_inventario',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
