# Generated by Django 3.0.7 on 2020-11-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_auto_20201118_0320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaCuenta',
        ),
        migrations.DeleteModel(
            name='CicloContable',
        ),
        migrations.DeleteModel(
            name='CostoCif',
        ),
        migrations.DeleteModel(
            name='CostoIndirecto',
        ),
        migrations.DeleteModel(
            name='CostoInventario',
        ),
        migrations.DeleteModel(
            name='CostoMod',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Mayorizado',
        ),
        migrations.DeleteModel(
            name='PartidaCuenta',
        ),
        migrations.DeleteModel(
            name='PartidaDiario',
        ),
        migrations.DeleteModel(
            name='TipoCuenta',
        ),
        migrations.DeleteModel(
            name='TransaccionInventario',
        ),
    ]
